// GENERATED by tools/gather.py — DO NOT EDIT.
// Edit tools/gather.py (plan_opencode_plugin) and re-run the gather.
/**
 * awow plugin for opencode.
 *
 * Two jobs, mirroring what the Claude Code plugin gets from its SessionStart hook:
 *
 *  1. Register the commands-as-skills payload. opencode plugins are JS hook
 *     modules — no manifest field can declare a skills directory — so the only
 *     way in is the `config` hook, which mutates the cached config singleton
 *     before skills are lazily discovered.
 *  2. Inject the using-awow operating reflex, plus an opencode tool mapping.
 *     A global install lands in repos with no repo-root AGENTS.md; without this
 *     awow would be installed but dormant.
 */

import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// .opencode/plugins/ -> the payload root. agent-skills/ is the same directory
// Pi loads via pi.skills, so both harnesses see one copy with one token channel
// ({AWOW_ROOT} -> ../.., {AWOW_TOOLS} -> ../../tools).
const PACKAGE_ROOT = path.resolve(__dirname, '../..');
const SKILLS_DIR = path.join(PACKAGE_ROOT, 'agent-skills');
const BOOTSTRAP_PATH = path.join(SKILLS_DIR, 'using-awow', 'SKILL.md');
const MARKER = 'awow-operating-reflex';

const stripFrontmatter = (text) => {
  const m = text.match(/^---\n[\s\S]*?\n---\n([\s\S]*)$/);
  return m ? m[1] : text;
};

const TOOL_MAPPING = [
  '**Tool mapping for opencode.** Where awow names a Claude Code tool, use:',
  '- Read / Write / Edit a file -> `read` / `write` / `edit`',
  '- Run a shell command -> `bash`',
  '- Track multi-step work -> `todowrite`',
  '- Dispatch a subagent -> `task`',
  '- Invoke a skill -> the native `skill` tool',
].join('\n');

// The SKILL.md does not change during a session, so read and parse it once.
let _cache;

const bootstrap = () => {
  if (_cache !== undefined) return _cache;
  if (!fs.existsSync(BOOTSTRAP_PATH)) {
    // Fail loud, not soft. The 0.5.0 payload shipped a one-line error quietly
    // standing in for the whole reflex; a missing bootstrap must be
    // unmistakable both in the injected context and on stderr.
    const err =
      'awow: using-awow bootstrap NOT FOUND at ' + BOOTSTRAP_PATH +
      '. The operating reflex did NOT load — this plugin build is broken.';
    console.error(err);
    _cache = '<' + MARKER + '>\n' + err + '\n</' + MARKER + '>';
    return _cache;
  }
  const body = stripFrontmatter(fs.readFileSync(BOOTSTRAP_PATH, 'utf8')).trim();
  _cache = '<' + MARKER + '>\n' + body + '\n\n' + TOOL_MAPPING + '\n</' + MARKER + '>';
  return _cache;
};

export const AwowPlugin = async () => ({
  config: async (config) => {
    config.skills = config.skills || {};
    config.skills.paths = config.skills.paths || [];
    if (!config.skills.paths.includes(SKILLS_DIR)) {
      config.skills.paths.push(SKILLS_DIR);
    }
  },

  // Inject into the first user message rather than a system message: opencode
  // reloads messages from the DB on every agent step, and repeated system
  // messages both bloat tokens and break some models.
  'experimental.chat.messages.transform': async (_input, output) => {
    const text = bootstrap();
    if (!text || !output.messages || !output.messages.length) return;
    const firstUser = output.messages.find((m) => m.info.role === 'user');
    if (!firstUser || !firstUser.parts.length) return;
    // Guard against double injection when an already-transformed array is
    // passed through the hook again.
    if (firstUser.parts.some((p) => p.type === 'text' && p.text.includes(MARKER))) return;
    const ref = firstUser.parts[0];
    firstUser.parts.unshift({ ...ref, type: 'text', text });
  },
});
